title: Kol Documentation
description: Information for kol store 
theme: just-the-docs

url: https://ytyeoh.github.io/kol_doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
